Repository TacticalTrainingTeam/ttt_a3, pull requests merged in 2025-02, with the labels that each got.

#205 compat_xeh - update required addons
  addons/compat_xeh_fix/config.cpp
Labels: bug fix

#206 tools - add files for use of arma debug engine
  .hemtt/launch.toml
  .vscode/launch.json
Labels: tools

#207 common - add callReinforcements
  .hemtt/missions/ttt_test.VR/init.sqf
  .hemtt/missions/ttt_test.VR/initServer.sqf
  .hemtt/missions/ttt_test.VR/mission.sqm
  addons/common/XEH_PREP.hpp
  addons/common/config.cpp
  addons/common/functions/fnc_callReinforcements.sqf
  addons/common/readme.md
  addons/intel/functions/fnc_addIntel.sqf
Labels: feature request

#208 kurzer readme fix
  addons/common/readme.md
Labels: enhancement

#175 vests - improve config
  addons/vests/CfgVehicles.hpp
  addons/vests/CfgWeapons.hpp
  addons/vests/config.cpp
Labels: enhancement

#176 helmets - improve configs
  addons/helmets/CfgVehicles.hpp
  addons/helmets/CfgWeapons.hpp
  addons/helmets/config.cpp
Labels: enhancement

#177 backpacks - improve configs
  addons/backpacks/CfgVehicles.hpp
Labels: enhancement

#178 Berets - improve config
  addons/berets/CfgWeapons.hpp
  addons/berets/data/berets_blau_co.paa
  addons/berets/data/berets_braun_co.paa
  addons/berets/data/berets_bronze_co.paa
  addons/berets/data/berets_gelb_co.paa
  addons/berets/data/berets_gold_co.paa
  addons/berets/data/berets_grau_co.paa
  addons/berets/data/berets_gruen_co.paa
  addons/berets/data/berets_logo_co.paa
  addons/berets/data/berets_orange_co.paa
  addons/berets/data/berets_platin_co.paa
  addons/berets/data/berets_rot_co.paa
  addons/berets/data/berets_schwarz_co.paa
  addons/berets/data/berets_silber_co.paa
  addons/berets/data/berets_violett_co.paa
  addons/berets/data/berets_weiss_co.paa
  addons/berets/data/previews/berets_blau_icon_co.paa
  addons/berets/data/previews/berets_braun_icon_co.paa
  addons/berets/data/previews/berets_bronze_icon_co.paa
  addons/berets/data/previews/berets_gelb_icon_co.paa
  addons/berets/data/previews/berets_gold_icon_co.paa
  addons/berets/data/previews/berets_grau_icon_co.paa
  addons/berets/data/previews/berets_gruen_icon_co.paa
  addons/berets/data/previews/berets_logo_icon_co.paa
  addons/berets/data/previews/berets_orange_icon_co.paa
  addons/berets/data/previews/berets_platin_icon_co.paa
  addons/berets/data/previews/berets_rot_icon_co.paa
  addons/berets/data/previews/berets_schwarz_icon_co.paa
  addons/berets/data/previews/berets_silber_icon_co.paa
  addons/berets/data/previews/berets_violett_icon_co.paa
  addons/berets/data/previews/berets_weiss_icon_co.paa
Labels: enhancement

#198 general - improve sqfc support
  addons/compat_rhs_weapons/CfgEventhandlers.hpp
  addons/w_buildingshield/CfgEventHandlers.hpp
  addons/w_vehicleshield/CfgEventHandlers.hpp
Labels: enhancement

#200 general - improve script_component.hpp include to be relative
  addons/advancedslingloading/functions/fnc_initAdvancedSlingLoading.sqf
  addons/advancedslingloading/functions/script_component.hpp
  addons/advancedtowing/functions/fnc_initAdvancedTowing.sqf
  addons/advancedtowing/functions/script_component.hpp
  addons/compat_rhs_weapons/functions/fnc_addACEActions.sqf
  addons/compat_rhs_weapons/functions/fnc_switchGoggles.sqf
  addons/compat_rhs_weapons/functions/fnc_switchVisor.sqf
  addons/compat_rhs_weapons/functions/script_component.hpp
  addons/discord_richpresence/functions/fnc_updateRichPresence.sqf
  addons/discord_richpresence/functions/script_component.hpp
  addons/dismantle/functions/fnc_addActions.sqf
  addons/dismantle/functions/fnc_canDismantle.sqf
  addons/dismantle/functions/fnc_dismantleProgressbar.sqf
  addons/grad_screenshotmode/functions/fnc_addHelpRecord.sqf
  addons/grad_screenshotmode/functions/fnc_toggleACENametags.sqf
  addons/grad_screenshotmode/functions/fnc_toggleAll.sqf
  addons/grad_screenshotmode/functions/fnc_toggleVanillaHUD.sqf
  addons/grad_screenshotmode/functions/script_component.hpp
  addons/main/functions/fnc_callGlobalFnc.sqf
  addons/spotlight_cup/functions/fnc_joinServer.sqf
  addons/spotlight_cup/functions/script_component.hpp
  addons/spotlight_event/functions/fnc_joinServer.sqf
  addons/spotlight_rhs/functions/fnc_joinServer.sqf
  addons/spotlight_rhs/functions/script_component.hpp
  addons/teleport/functions/fnc_addActions.sqf
  addons/teleport/functions/fnc_createTeleporter.sqf
  addons/teleport/functions/script_component.hpp
  addons/w_buildingshield/functions/fnc_buildingShield.sqf
  addons/w_buildingshield/functions/fnc_moduleBuildingShield.sqf
  addons/w_buildingshield/functions/fnc_removeWindowGlasses.sqf
  addons/w_buildingshield/functions/script_component.hpp
  addons/w_teleporter/functions/fnc_addAction.sqf
  addons/w_teleporter/functions/fnc_onButtonTeleportClick.sqf
  addons/w_teleporter/functions/fnc_onListOptionsSelChanged.sqf
  addons/w_teleporter/functions/fnc_onListPlayersSelChanged.sqf
  addons/w_teleporter/functions/fnc_onLoad.sqf
  addons/w_teleporter/functions/script_component.hpp
  addons/w_vehicleshield/functions/fnc_addVehicleShield.sqf
  addons/w_vehicleshield/functions/script_component.hpp
Labels: enhancement

#210 rsr - fix texture and stringtable erros
  addons/rsr/retex_bwa3/CfgVehicles.hpp
  addons/rsr/retex_bwa3/stringtable.xml
  addons/rsr/retex_cup/CfgVehicles.hpp
  addons/rsr/retex_cup/CfgWeapons.hpp
  addons/rsr/retex_cup/stringtable.xml
  addons/rsr/retex_itc/CfgVehicles.hpp
  addons/rsr/retex_itc/config.cpp
  addons/rsr/retex_itc/stringtable.xml
  addons/rsr/retex_rhs/CfgVehicles.hpp
  addons/rsr/retex_rhs/stringtable.xml
  addons/rsr/retex_vanilla/CfgVehicles.hpp
  addons/rsr/retex_vanilla/config.cpp
  addons/rsr/retex_vanilla/stringtable.xml
  addons/uniforms/CfgWeapons.hpp
  addons/uniforms/data/pictures/ttt_uniform_silver_bw_tropen.paa
Labels: bug fix

#211 compat xeh fix - fix `SUBADDON` configs
  addons/compat_xeh_fix/compat_breach/config.cpp
  addons/compat_xeh_fix/compat_bwmod/config.cpp
  addons/compat_xeh_fix/compat_fir_aws/config.cpp
  addons/compat_xeh_fix/compat_pbw/config.cpp
  addons/compat_xeh_fix/compat_rnt/config.cpp
  addons/compat_xeh_fix/compat_vanilla/config.cpp
Labels: bug fix

#219 general - sort stringtables
  addons/advancedtowing/stringtable.xml
  addons/compat_3cb_vehicles/stringtable.xml
  addons/medic_backpack/stringtable.xml
  addons/medic_vehicle/stringtable.xml
  addons/teleport/stringtable.xml
  addons/uniforms/stringtable.xml
Labels: enhancement

#204 teleporter - Add removal of all items from player when entering spectator
  addons/teleport/functions/fnc_addActions.sqf
  addons/teleport/stringtable.xml
Labels: pr/feature

#172 general - bump version number
  addons/main/script_version.hpp
Labels: ignore-changelog

#218 compat_xeh - fix subaddons
  addons/compat_xeh_fix/compat_xeh_fix_breach/CfgVehicles.hpp
  addons/compat_xeh_fix/compat_xeh_fix_breach/config.cpp
  addons/compat_xeh_fix/compat_xeh_fix_breach/readme.md
  addons/compat_xeh_fix/compat_xeh_fix_breach/script_component.hpp
  addons/compat_xeh_fix/compat_xeh_fix_bwmod/CfgVehicles.hpp
  addons/compat_xeh_fix/compat_xeh_fix_bwmod/config.cpp
  addons/compat_xeh_fix/compat_xeh_fix_bwmod/readme.md
  addons/compat_xeh_fix/compat_xeh_fix_bwmod/script_component.hpp
  addons/compat_xeh_fix/compat_xeh_fix_fir_aws/CfgVehicles.hpp
  addons/compat_xeh_fix/compat_xeh_fix_fir_aws/config.cpp
  addons/compat_xeh_fix/compat_xeh_fix_fir_aws/readme.md
  addons/compat_xeh_fix/compat_xeh_fix_fir_aws/script_component.hpp
  addons/compat_xeh_fix/compat_xeh_fix_pbw/CfgVehicles.hpp
  addons/compat_xeh_fix/compat_xeh_fix_pbw/config.cpp
  addons/compat_xeh_fix/compat_xeh_fix_pbw/readme.md
  addons/compat_xeh_fix/compat_xeh_fix_pbw/script_component.hpp
  addons/compat_xeh_fix/compat_xeh_fix_rnt/CfgVehicles.hpp
  addons/compat_xeh_fix/compat_xeh_fix_rnt/config.cpp
  addons/compat_xeh_fix/compat_xeh_fix_rnt/readme.md
  addons/compat_xeh_fix/compat_xeh_fix_rnt/script_component.hpp
  addons/compat_xeh_fix/compat_xeh_fix_vanilla/CfgVehicles.hpp
  addons/compat_xeh_fix/compat_xeh_fix_vanilla/config.cpp
  addons/compat_xeh_fix/compat_xeh_fix_vanilla/readme.md
  addons/compat_xeh_fix/compat_xeh_fix_vanilla/script_component.hpp
Labels: pr/bug-fix

#222 general - Changed `_this` from calls that did not need it
  addons/advancedslingloading/functions/fnc_initAdvancedSlingLoading.sqf
  addons/advancedtowing/functions/fnc_initAdvancedTowing.sqf
Labels: pr/cleanup

#230 general - add `VERSION_CONFIG;` to addons
  addons/advancedslingloading/config.cpp
  addons/advancedtowing/config.cpp
  addons/backpacks/config.cpp
  addons/berets/config.cpp
  addons/compat_3cb_vehicles/config.cpp
  addons/compat_bwa3_vehicles/config.cpp
  addons/compat_cfp_vehicles/config.cpp
  addons/compat_cfp_weapons/config.cpp
  addons/compat_cup_vehicles/config.cpp
  addons/compat_rhs_ammo/config.cpp
  addons/compat_rhs_weapons/config.cpp
  addons/compat_vanilla_ammo/config.cpp
  addons/compat_vanilla_vehicles/config.cpp
  addons/compat_vanilla_weapons/config.cpp
  addons/compat_xeh_fix/compat_xeh_fix_breach/config.cpp
  addons/compat_xeh_fix/compat_xeh_fix_bwmod/config.cpp
  addons/compat_xeh_fix/compat_xeh_fix_fir_aws/config.cpp
  addons/compat_xeh_fix/compat_xeh_fix_pbw/config.cpp
  addons/compat_xeh_fix/compat_xeh_fix_rnt/config.cpp
  addons/compat_xeh_fix/compat_xeh_fix_vanilla/config.cpp
  addons/discord_richpresence/config.cpp
  addons/dismantle/config.cpp
  addons/grad_screenshotmode/config.cpp
  addons/helmets/config.cpp
  addons/insignias/config.cpp
  addons/intel/config.cpp
  addons/main/config.cpp
  addons/medic_backpack/config.cpp
  addons/medic_vehicle/config.cpp
  addons/repair_vehicle/config.cpp
  addons/rsr/config.cpp
  addons/rsr/retex_bwa3/config.cpp
  addons/rsr/retex_cup/config.cpp
  addons/rsr/retex_itc/config.cpp
  addons/rsr/retex_rhs/config.cpp
  addons/rsr/retex_vanilla/config.cpp
  addons/signalpanel/config.cpp
  addons/signs/config.cpp
  addons/spotlight_cup/config.cpp
  addons/spotlight_event/config.cpp
  addons/spotlight_rhs/config.cpp
  addons/teleport/config.cpp
  addons/uniforms/config.cpp
  addons/vests/config.cpp
Labels: pr/cleanup

#228 compat_bwa3 - change name
  addons/compat_bwa3/$PBOPREFIX$
  addons/compat_bwa3/CfgVehicles.hpp
  addons/compat_bwa3/config.cpp
  addons/compat_bwa3/readme.md
  addons/compat_bwa3/script_component.hpp
  addons/compat_bwa3/stringtable.xml
  addons/compat_bwa3_vehicles/$PBOPREFIX$
Labels: pr/change

#237 compat_xeh_fix - Add XEH fix for jbad, RnT 120mm
  addons/compat_xeh_fix/compat_xeh_fix_jbad/CfgVehicles.hpp
  addons/compat_xeh_fix/compat_xeh_fix_jbad/config.cpp
  addons/compat_xeh_fix/compat_xeh_fix_jbad/readme.md
  addons/compat_xeh_fix/compat_xeh_fix_jbad/script_component.hpp
  addons/compat_xeh_fix/compat_xeh_fix_rnt/CfgVehicles.hpp
  addons/compat_xeh_fix/readme.md
Labels: pr/feature

#240 tools - Add 3 new tools and improves config checker tool
  tools/config_style_checker.py
  tools/search_privates.py
  tools/search_undefined_function.py
  tools/search_unused_privates.py
Labels: tools, ignore-changelog

#241 backpacks - Add previews
  addons/backpacks/CfgVehicles.hpp
  addons/backpacks/data/pictures/ttt_backpack_radio_bronze_us_desert.paa
  addons/backpacks/data/pictures/ttt_backpack_radio_brown_us_desert.paa
  addons/backpacks/data/pictures/ttt_backpack_radio_coyote.paa
  addons/backpacks/data/pictures/ttt_backpack_radio_gold_us_desert.paa
  addons/backpacks/data/pictures/ttt_backpack_radio_green_us_desert.paa
  addons/backpacks/data/pictures/ttt_backpack_radio_grey_us_desert.paa
  addons/backpacks/data/pictures/ttt_backpack_radio_olive.paa
  addons/backpacks/data/pictures/ttt_backpack_radio_platinum_us_desert.paa
  addons/backpacks/data/pictures/ttt_backpack_radio_silver_us_desert.paa
  addons/backpacks/data/pictures/ttt_backpack_radio_white_us_desert.paa
  addons/backpacks/data/pictures/ttt_backpack_radio_yellow_us_desert.paa
Labels: pr/feature

#242 vests - Add previews
  addons/vests/CfgWeapons.hpp
  addons/vests/data/pictures/ttt_Vest_Crew_Bronze.paa
  addons/vests/data/pictures/ttt_Vest_Crew_Silver.paa
  addons/vests/data/pictures/ttt_Vest_Crew_White.paa
  addons/vests/data/pictures/ttt_Vest_Heavy_Black_US_Desert.paa
  addons/vests/data/pictures/ttt_Vest_Heavy_Blue_US_Desert.paa
  addons/vests/data/pictures/ttt_Vest_Heavy_Brown_US_Desert.paa
  addons/vests/data/pictures/ttt_Vest_Heavy_Gold_US_Desert.paa
  addons/vests/data/pictures/ttt_Vest_Heavy_Green_US_Desert.paa
  addons/vests/data/pictures/ttt_Vest_Heavy_Grey_US_Desert.paa
  addons/vests/data/pictures/ttt_Vest_Heavy_Orange_US_Desert.paa
  addons/vests/data/pictures/ttt_Vest_Heavy_Red_US_Desert.paa
  addons/vests/data/pictures/ttt_Vest_Heavy_Violet_US_Desert.paa
  addons/vests/data/pictures/ttt_Vest_Heavy_Yellow_US_Desert.paa
  addons/vests/data/pictures/ttt_Vest_Lite_Black_US_Desert.paa
  addons/vests/data/pictures/ttt_Vest_Lite_Blue_US_Desert.paa
  addons/vests/data/pictures/ttt_Vest_Lite_Brown_US_Desert.paa
  addons/vests/data/pictures/ttt_Vest_Lite_Gold_US_Desert.paa
  addons/vests/data/pictures/ttt_Vest_Lite_Green_US_Desert.paa
  addons/vests/data/pictures/ttt_Vest_Lite_Grey_US_Desert.paa
  addons/vests/data/pictures/ttt_Vest_Lite_Orange_US_Desert.paa
  addons/vests/data/pictures/ttt_Vest_Lite_Red_US_Desert.paa
  addons/vests/data/pictures/ttt_Vest_Lite_Violet_US_Desert.paa
  addons/vests/data/pictures/ttt_Vest_Lite_Yellow_US_Desert.paa
Labels: pr/feature

#243 main - minor cleanup
  addons/main/XEH_PREP.hpp
  addons/main/config.cpp
  addons/main/functions/fnc_callGlobalFnc.sqf
Labels: pr/cleanup

#245 general - remove unused stringtables
  addons/advancedtowing/stringtable.xml
  addons/compat_3cb_vehicles/stringtable.xml
Labels: pr/cleanup

#244 general - bump version number
  addons/main/script_version.hpp
Labels: ignore-changelog

#221 tools - Improve readme, contributing, templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/enhancement_request.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/main.yml
  CONTRIBUTING
  CONTRIBUTING.md
  readme.md
Labels: tools

#247 tools - Improve Tools
  .github/workflows/main.yml
  .vscode/tasks.json
  tools/check_strings.py
  tools/search_privates.py
  tools/search_undefined_function.py
Labels: tools

#254 clearhud - Change DIK include
  addons/clearhud/functions/fnc_registerChatKeybind.sqf
  addons/clearhud/functions/fnc_toggleChat.sqf
  include/a3/ui_f/hpp/defineDIKCodes.inc
Labels: pr/change

#253 Uniforms - Change scope of uniforms to hide them in 3DEN
  addons/uniforms/CfgVehicles.hpp
  addons/uniforms/CfgWeapons.hpp
Labels: pr/enhancement
