Repository TacticalTrainingTeam/ttt_a3, pull requests merged in 2025-03, with the labels that each got.

#252 rsr_retex_cup - Fix snowcamo picture path
  addons/rsr/rsr_retex_cup/CfgWeapons.hpp
Labels: pr/bug-fix

#246 general - Improve author Information
  addons/grad_screenshotmode/config.cpp
  addons/intel/script_component.hpp
  addons/rsr/readme.md
  addons/rsr/script_component.hpp
  addons/spotlight_cup/config.cpp
  addons/spotlight_event/config.cpp
  addons/w_buildingshield/config.cpp
  addons/w_buildingshield/script_component.hpp
  addons/w_teleporter/config.cpp
  addons/w_vehicleshield/config.cpp
  addons/w_vehicleshield/script_component.hpp
Labels: pr/enhancement

#258 tools - Improve unused privates checking script
  tools/search_unused_privates.py
Labels: tools

#251 Advanced Towing - Fix All Caps Warning in `SA_TOW_SUPPORTED_VEHICLES`
  addons/advancedtowing/functions/fnc_initAdvancedTowing.sqf
Labels: pr/change

#234 compat_bwa3 - Add ACRE Configs
  addons/common/XEH_PREP.hpp
  addons/common/functions/fnc_noApiFunction.sqf
  addons/common/stringtable.xml
  addons/compat_bwa3/CfgVehicles.hpp
  addons/compat_bwa3/config.cpp
  addons/compat_bwa3/readme.md
Labels: pr/feature

#236 compat_cup_vehicles - Add ACRE Config to Boxer, Leopard 1, Leopard 2
  addons/compat_cup_vehicles/CfgVehicles.hpp
  addons/compat_cup_vehicles/script_component.hpp
Labels: pr/feature

#227 compat_vanilla - Change structure
  addons/compat_vanilla/$PBOPREFIX$
  addons/compat_vanilla/CfgAmmo.hpp
  addons/compat_vanilla/CfgVehicles.hpp
  addons/compat_vanilla/CfgWeapons.hpp
  addons/compat_vanilla/config.cpp
  addons/compat_vanilla/readme.md
  addons/compat_vanilla/script_component.hpp
  addons/compat_vanilla/stringtable.xml
  addons/compat_vanilla_ammo/$PBOPREFIX$
  addons/compat_vanilla_ammo/readme.md
  addons/compat_vanilla_vehicles/$PBOPREFIX$
  addons/compat_vanilla_vehicles/config.cpp
  addons/compat_vanilla_vehicles/readme.md
  addons/compat_vanilla_vehicles/script_component.hpp
  addons/compat_vanilla_weapons/$PBOPREFIX$
  addons/compat_vanilla_weapons/config.cpp
  addons/compat_vanilla_weapons/readme.md
  addons/compat_vanilla_weapons/script_component.hpp
Labels: pr/change

#225 compat_cfp - Change structure
  addons/compat_cfp/$PBOPREFIX$
  addons/compat_cfp/compat_cfp_logistics/CfgVehicles.hpp
  addons/compat_cfp/compat_cfp_logistics/CfgWeapons.hpp
  addons/compat_cfp/compat_cfp_logistics/README.md
  addons/compat_cfp/compat_cfp_logistics/config.cpp
  addons/compat_cfp/compat_cfp_logistics/script_component.hpp
  addons/compat_cfp/config.cpp
  addons/compat_cfp/readme.md
  addons/compat_cfp/script_component.hpp
  addons/compat_cfp_vehicles/CfgVehicles.hpp
  addons/compat_cfp_vehicles/readme.md
  addons/compat_cfp_weapons/$PBOPREFIX$
  addons/compat_cfp_weapons/config.cpp
  addons/compat_cfp_weapons/readme.md
  addons/compat_cfp_weapons/script_component.hpp
Labels: pr/change

#226 compat_rhs - Change structure
  addons/compat_rhs/$PBOPREFIX$
  addons/compat_rhs/CfgAmmo.hpp
  addons/compat_rhs/CfgEventhandlers.hpp
  addons/compat_rhs/XEH_PREP.hpp
  addons/compat_rhs/XEH_postInit.sqf
  addons/compat_rhs/XEH_preInit.sqf
  addons/compat_rhs/XEH_preStart.sqf
  addons/compat_rhs/config.cpp
  addons/compat_rhs/functions/fnc_addACEActions.sqf
  addons/compat_rhs/functions/fnc_handleSlotItemChanged.sqf
  addons/compat_rhs/functions/fnc_switchGoggles.sqf
  addons/compat_rhs/functions/fnc_switchVisor.sqf
  addons/compat_rhs/readme.md
  addons/compat_rhs/script_component.hpp
  addons/compat_rhs/stringtable.xml
  addons/compat_rhs_ammo/$PBOPREFIX$
  addons/compat_rhs_ammo/readme.md
  addons/compat_rhs_ammo/script_component.hpp
  addons/compat_rhs_weapons/$PBOPREFIX$
  addons/compat_rhs_weapons/CfgWeapons.hpp
  addons/compat_rhs_weapons/config.cpp
Labels: pr/change

#265 compat_cfp_logistics - Fix loading
  addons/compat_cfp/compat_cfp_logistics/config.cpp
Labels: pr/bug-fix, ignore-changelog

#262 general - sort stringtables
  addons/common/stringtable.xml
Labels: ignore-changelog

#263 bump version
  addons/main/script_version.hpp
Labels: ignore-changelog

#266 tools - Add latest.zip to release on publish
  .github/workflows/release.yml
Labels: tools

#271 compat_rhs - Change call
  addons/compat_rhs/CfgEventhandlers.hpp
Labels: pr/cleanup

#274 tools - Add recommended extensions
  .vscode/extensions.json
  readme.md
Labels: tools

#216 effects - Add new component
  .hemtt/missions/ttt_test.Malden/mission.sqm
  .hemtt/missions/ttt_test.VR/mission.sqm
  addons/effects/$PBOPREFIX$
  addons/effects/CfgEventHandlers.hpp
  addons/effects/CfgSounds.hpp
  addons/effects/XEH_PREP.hpp
  addons/effects/XEH_preInit.sqf
  addons/effects/XEH_preStart.sqf
  addons/effects/config.cpp
  addons/effects/functions/fnc_condensedBreath.sqf
  addons/effects/functions/fnc_snow.sqf
  addons/effects/functions/fnc_stormEffects.sqf
  addons/effects/functions/fnc_stormInit.sqf
  addons/effects/readme.md
  addons/effects/script_component.hpp
Labels: pr/feature

#275 insignias_tagging - Add TTT emblems to ace tagging
  addons/insignias/insignias_tagging/CfgTags.hpp
  addons/insignias/insignias_tagging/config.cpp
  addons/insignias/insignias_tagging/readme.md
  addons/insignias/insignias_tagging/script_component.hpp
Labels: pr/feature

#276 compat_rhs - Fix macro padding
  addons/compat_rhs/CfgEventhandlers.hpp
Labels: ignore-changelog

#273 tools - Add a notice to discord channel action
  .github/workflows/discord-notice.yml
Labels: tools

#277 tools - fix version of github action
  .github/workflows/discord-notice.yml
Labels: tools

#280 insignias - Improve Insignias & Tagging
  addons/insignias/CfgUnitInsignia.hpp
  addons/insignias/insignias_tagging/CfgTags.hpp
  addons/insignias/insignias_tagging/CfgWeapons.hpp
  addons/insignias/insignias_tagging/config.cpp
  addons/insignias/insignias_tagging/readme.md
  addons/insignias/insignias_tagging/script_component.hpp
  addons/insignias/insignias_tagging/stringtable.xml
  addons/insignias/stringtable.xml
Labels: pr/enhancement

#233 compat_3cb_factions - Add new component
  addons/compat_3cb_factions/$PBOPREFIX$
  addons/compat_3cb_factions/compat_3cb_factions_trenches/CfgVehicles.hpp
  addons/compat_3cb_factions/compat_3cb_factions_trenches/README.md
  addons/compat_3cb_factions/compat_3cb_factions_trenches/config.cpp
  addons/compat_3cb_factions/compat_3cb_factions_trenches/script_component.hpp
  addons/compat_3cb_factions/config.cpp
  addons/compat_3cb_factions/readme.md
  addons/compat_3cb_factions/script_component.hpp
Labels: pr/feature

#232 compat_cup_units - Add new component
  addons/compat_cup_units/$PBOPREFIX$
  addons/compat_cup_units/compat_cup_units_trenches/CfgVehicles.hpp
  addons/compat_cup_units/compat_cup_units_trenches/CfgWeapons.hpp
  addons/compat_cup_units/compat_cup_units_trenches/README.md
  addons/compat_cup_units/compat_cup_units_trenches/config.cpp
  addons/compat_cup_units/compat_cup_units_trenches/script_component.hpp
  addons/compat_cup_units/config.cpp
  addons/compat_cup_units/readme.md
  addons/compat_cup_units/script_component.hpp
Labels: pr/feature

#281 general - prepare-release
  addons/common/stringtable.xml
  addons/insignias/stringtable.xml
  addons/main/script_version.hpp
Labels: ignore-changelog

#282 compat_cup_units - fix skip when cup is not loaded
  addons/compat_cup_units/config.cpp
  addons/main/script_version.hpp
Labels: pr/bug-fix

#283 rsr - Fix texture path error
  addons/rsr/CfgFactionClasses.hpp
Labels: pr/bug-fix

#289 compat_xeh - update compat for new breach version
  addons/compat_xeh_fix/compat_xeh_fix_breach/CfgVehicles.hpp
  addons/compat_xeh_fix/compat_xeh_fix_breach/config.cpp
Labels: pr/change

#290 insignias_tagging - Fix filename
  addons/insignias/insignias_tagging/CfgTags.hpp
Labels: pr/bug-fix

#278 effects - Add effects module
  .hemtt/missions/ttt_test.VR/mission.sqm
  addons/common/CfgFactionsClasses.hpp
  addons/effects/CfgEventHandlers.hpp
  addons/effects/CfgVehicles.hpp
  addons/effects/XEH_PREP.hpp
  addons/effects/XEH_postInit.sqf
  addons/effects/config.cpp
  addons/effects/functions/fnc_condensedBreath.sqf
  addons/effects/functions/fnc_snow.sqf
  addons/effects/functions/fnc_snowModule.sqf
  addons/effects/functions/fnc_stormInit.sqf
  addons/effects/functions/fnc_stormInitModule.sqf
  addons/effects/functions/fnc_zenRegister.sqf
  addons/effects/readme.md
  addons/effects/stringtable.xml
Labels: pr/feature
