Repository TacticalTrainingTeam/ttt_a3, pull requests merged in 2025-08, with the labels that each got.

#403 Backpacks - Add larger Medic Bagpack
  addons/backpacks/CfgVehicles.hpp
  addons/backpacks/config.cpp
  addons/backpacks/data/TTT_01_backpack_fast_rgr_co.paa
  addons/backpacks/data/TTT_01_backpack_fast_tan_co.paa
  addons/backpacks/data/TTT_02_backpack_fast_rgr_co.paa
  addons/backpacks/data/TTT_02_backpack_fast_tan_co.paa
  addons/backpacks/data/TTT_03_backpack_fast_rgr_co.paa
  addons/backpacks/data/TTT_03_backpack_fast_tan_co.paa
  addons/backpacks/data/pictures/ttt_01_backpack_fast_tan_co_ca.jpg
  addons/backpacks/data/pictures/ttt_02_backpack_fast_tan_co_ca.jpg
  addons/backpacks/data/pictures/ttt_03_backpack_fast_tan_co_ca.jpg
  addons/backpacks/readme.md
  addons/backpacks/stringtable.xml
Labels: pr/feature

#414 common - Add medic crates to config.cpp
  addons/common/config.cpp
Labels: pr/bug-fix

#417 prepare release
  addons/main/script_version.hpp
Labels: ignore-changelog

#418 tools - Add link to docs to release drafter
  .github/release-drafter.yml
Labels: tools

#420 docs - Fix internal Link
  docs/addons/common/objects.md
Labels: pr/documentation
