Repository TacticalTrainingTeam/ttt_a3, pull requests merged in 2025-01, with the labels that each got.

#91 teleport - disable damage to teleporter obj
  addons/teleport/functions/fnc_createTeleporter.sqf
Labels: enhancement

#109 Compat Vanilla: Add Incrase Flare Brightness + rebalance bouncyness
  addons/compat_rhs_no40mmsmokebounce/CfgAmmo.hpp
  addons/compat_vanilla_no40mmsmokebounce/CfgAmmo.hpp
  addons/compat_vanilla_no40mmsmokebounce/config.cpp
  addons/compat_vanilla_no40mmsmokebounce/readme.md
  addons/compat_vanilla_no40mmsmokebounce/script_component.hpp
Labels: feature request

#110 New Component: Add w-building-shield
  .hemtt/missions/ttt_test.VR/mission.sqm
  addons/main/CfgFactionsClasses.hpp
  addons/main/config.cpp
  addons/w_buildingshield/$PBOPREFIX$
  addons/w_buildingshield/Cfg3DEN.hpp
  addons/w_buildingshield/CfgEventHandlers.hpp
  addons/w_buildingshield/CfgVehicles.hpp
  addons/w_buildingshield/XEH_PREP.hpp
  addons/w_buildingshield/XEH_postInit.sqf
  addons/w_buildingshield/XEH_preInit.sqf
  addons/w_buildingshield/XEH_preStart.sqf
  addons/w_buildingshield/config.cpp
  addons/w_buildingshield/functions/defines.inc
  addons/w_buildingshield/functions/fnc_buildingShield.sqf
  addons/w_buildingshield/functions/fnc_moduleBuildingShield.sqf
  addons/w_buildingshield/functions/fnc_removeWindowGlasses.sqf
  addons/w_buildingshield/functions/script_component.hpp
  addons/w_buildingshield/readme.md
  addons/w_buildingshield/script_component.hpp
  addons/w_buildingshield/stringtable.xml
Labels: feature request

#94 uniforms - Add green alt uniform
  addons/uniforms/CfgVehicles.hpp
  addons/uniforms/CfgWeapons.hpp
  addons/uniforms/config.cpp
  addons/uniforms/stringtable.xml
Labels: enhancement

#113 Add-w-vehicle-shield
  .hemtt/missions/~ttt_test.vr/mission.sqm
  addons/main/functions/fnc_callGlobalfFnc.sqf
  addons/main/functions/script_component.hpp
  addons/w_buildingshield/Cfg3DEN.hpp
  addons/w_vehicleshield/$PBOPREFIX$
  addons/w_vehicleshield/Cfg3DEN.hpp
  addons/w_vehicleshield/CfgEventHandlers.hpp
  addons/w_vehicleshield/XEH_PREP.hpp
  addons/w_vehicleshield/XEH_postInit.sqf
  addons/w_vehicleshield/XEH_preInit.sqf
  addons/w_vehicleshield/XEH_preStart.sqf
  addons/w_vehicleshield/config.cpp
  addons/w_vehicleshield/functions/fnc_vehicleShield.sqf
  addons/w_vehicleshield/functions/script_component.hpp
  addons/w_vehicleshield/readme.md
  addons/w_vehicleshield/script_component.hpp
  addons/w_vehicleshield/stringtable.xml
Labels: feature request

#114 vehicle / building Shield: fix displayname
  .hemtt/missions/~ttt_test.vr/mission.sqm
  addons/w_buildingshield/Cfg3DEN.hpp
  addons/w_buildingshield/stringtable.xml
  addons/w_vehicleshield/Cfg3DEN.hpp
  addons/w_vehicleshield/stringtable.xml
Labels: bug fix

#115 add meta cpp
  meta.cpp
Labels: enhancement

#86 main - add r_crate as fnc
  .hemtt/missions/ttt_test.VR/initServer.sqf
  .hemtt/missions/ttt_test.VR/mission.sqm
  addons/main/XEH_PREP.hpp
  addons/main/functions/fnc_crateFiller.sqf
Labels: feature request

#93 Insignias - add Insignias
  .hemtt/missions/ttt_test.VR/initPlayerLocal.sqf
  addons/backpacks/stringtable.xml
  addons/compat_vanilla_scopes/stringtable.xml
  addons/helmets/stringtable.xml
  addons/insignias/$PBOPREFIX$
  addons/insignias/CfgUnitInsignia.hpp
  addons/insignias/config.cpp
  addons/insignias/data/blau.paa
  addons/insignias/data/braun.paa
  addons/insignias/data/bronze.paa
  addons/insignias/data/eod_kontur.paa
  addons/insignias/data/gelb.paa
  addons/insignias/data/gold.paa
  addons/insignias/data/grau.paa
  addons/insignias/data/gruen.paa
  addons/insignias/data/orange.paa
  addons/insignias/data/platinum.paa
  addons/insignias/data/red_crystal_dark.paa
  addons/insignias/data/rot.paa
  addons/insignias/data/schwarz.paa
  addons/insignias/data/silber.paa
  addons/insignias/data/violett.paa
  addons/insignias/data/weiss.paa
  addons/insignias/readme.md
  addons/insignias/script_component.hpp
  addons/insignias/stringtable.xml
  addons/main/data/ttt_logo_blau_co.paa
  addons/main/data/ttt_logo_braun_co.paa
  addons/main/data/ttt_logo_bronze_co.paa
  addons/main/data/ttt_logo_gelb_co.paa
  addons/main/data/ttt_logo_gold_co.paa
  addons/main/data/ttt_logo_grau_co.paa
  addons/main/data/ttt_logo_gruen_co.paa
  addons/main/data/ttt_logo_orange_co.paa
  addons/main/data/ttt_logo_platin_co.paa
  addons/main/data/ttt_logo_rot_co.paa
  addons/main/data/ttt_logo_schwarz_co.paa
  addons/main/data/ttt_logo_sign_co.paa
  addons/main/data/ttt_logo_silber_co.paa
  addons/main/data/ttt_logo_violett_co.paa
  addons/main/data/ttt_logo_weiss_co.paa
  addons/rsr_bwa3/stringtable.xml
  addons/rsr_cup/stringtable.xml
  addons/rsr_itc_compat/stringtable.xml
  addons/rsr_rhs/stringtable.xml
  addons/rsr_vanilla/stringtable.xml
  addons/signs/CfgVehicles.hpp
  addons/signs/stringtable.xml
  addons/uniforms/stringtable.xml
  addons/vests/stringtable.xml
  addons/w_teleporter/stringtable.xml
Labels: feature request

#97 All Components: Add acre config to vehicles
  .hemtt/missions/ttt_test.VR/mission.sqm
  addons/compat_bwa3_vehicles/CfgVehicles.hpp
  addons/compat_cup_vehicles/CfgVehicles.hpp
  addons/compat_cup_vehicles/config.cpp
  addons/rsr_vanilla/CfgVehicles.hpp
Labels: feature request

#73 DRP - add setting to enable the update part
  .hemtt/missions/ttt_test.VR/cba_settings.sqf
  .hemtt/missions/ttt_test.VR/mission.sqm
  .hemtt/missions/ttt_test.VR/pbo.json
  addons/discord_richpresence/XEH_preInit.sqf
  addons/discord_richpresence/functions/fnc_updateRichPresence.sqf
  addons/discord_richpresence/readme.md
  addons/discord_richpresence/stringtable.xml
Labels: enhancement

#120 New Addon: add grad screenshotmode
  .hemtt/launch.toml
  addons/grad_screenshotmode/$PBOPREFIX$
  addons/grad_screenshotmode/XEH_PREP.hpp
  addons/grad_screenshotmode/XEH_postInit.sqf
  addons/grad_screenshotmode/XEH_preInit.sqf
  addons/grad_screenshotmode/XEH_preStart.sqf
  addons/grad_screenshotmode/cfgEventHandlers.hpp
  addons/grad_screenshotmode/config.cpp
  addons/grad_screenshotmode/functions/fnc_addHelpRecord.sqf
  addons/grad_screenshotmode/functions/fnc_toggleACENametags.sqf
  addons/grad_screenshotmode/functions/fnc_toggleAll.sqf
  addons/grad_screenshotmode/functions/fnc_toggleDuiHud.sqf
  addons/grad_screenshotmode/functions/fnc_toggleVanillaHUD.sqf
  addons/grad_screenshotmode/functions/script_component.hpp
  addons/grad_screenshotmode/readme.md
  addons/grad_screenshotmode/script_component.hpp
  addons/grad_screenshotmode/stringtable.xml
Labels: feature request

#122 Rename cfgEventHandlers.hpp to CfgEventHandlers.hpp
  addons/grad_screenshotmode/CfgEventHandlers.hpp
Labels: bug fix

#121 signalpanel: add new addon
  .hemtt/missions/ttt_test.VR/cba_settings.sqf
  .hemtt/missions/ttt_test.VR/mission.sqm
  addons/signalpanel/$PBOPREFIX$
  addons/signalpanel/CfgEventHandlers.hpp
  addons/signalpanel/XEH_PREP.hpp
  addons/signalpanel/XEH_postInit.sqf
  addons/signalpanel/XEH_preInit.sqf
  addons/signalpanel/XEH_preStart.sqf
  addons/signalpanel/config.cpp
  addons/signalpanel/functions/fnc_init.sqf
  addons/signalpanel/functions/script_component.hpp
  addons/signalpanel/initSettings.inc.sqf
  addons/signalpanel/readme.md
  addons/signalpanel/script_component.hpp
  addons/signalpanel/stringtable.xml
Labels: feature request

#72 medic* - Add medic_backpack and medic_vehicle
  .hemtt/launch.toml
  .hemtt/missions/ttt_test.VR/cba_settings.sqf
  .hemtt/missions/ttt_test.VR/init.sqf
  .hemtt/missions/ttt_test.VR/mission.sqm
  addons/medic_backpack/$PBOPREFIX$
  addons/medic_backpack/CfgEventHandlers.hpp
  addons/medic_backpack/XEH_PREP.hpp
  addons/medic_backpack/XEH_postInit.sqf
  addons/medic_backpack/XEH_preInit.sqf
  addons/medic_backpack/XEH_preStart.sqf
  addons/medic_backpack/config.cpp
  addons/medic_backpack/functions/fnc_addActions.sqf
  addons/medic_backpack/functions/fnc_canConstruct.sqf
  addons/medic_backpack/functions/fnc_canDeconstruct.sqf
  addons/medic_backpack/functions/fnc_cancel.sqf
  addons/medic_backpack/functions/fnc_planeConstruct.sqf
  addons/medic_backpack/functions/fnc_planeDeconstruct.sqf
  addons/medic_backpack/functions/fnc_progressbarConstruct.sqf
  addons/medic_backpack/functions/fnc_progressbarDeconstruct.sqf
  addons/medic_backpack/initSettings.inc.sqf
  addons/medic_backpack/readme.md
  addons/medic_backpack/script_component.hpp
  addons/medic_backpack/stringtable.xml
  addons/medic_vehicle/$PBOPREFIX$
  addons/medic_vehicle/CfgEventHandlers.hpp
  addons/medic_vehicle/XEH_PREP.hpp
  addons/medic_vehicle/XEH_postInit.sqf
  addons/medic_vehicle/XEH_preInit.sqf
  addons/medic_vehicle/XEH_preStart.sqf
  addons/medic_vehicle/config.cpp
  addons/medic_vehicle/functions/fnc_addActions.sqf
  addons/medic_vehicle/functions/fnc_canConstruct.sqf
  addons/medic_vehicle/functions/fnc_canDeconstruct.sqf
  addons/medic_vehicle/functions/fnc_cancel.sqf
  addons/medic_vehicle/functions/fnc_progressbarConstruct.sqf
  addons/medic_vehicle/functions/fnc_progressbarDeconstruct.sqf
  addons/medic_vehicle/functions/fnc_tentConstruct.sqf
  addons/medic_vehicle/functions/fnc_tentDeconstruct.sqf
  addons/medic_vehicle/initSettings.inc.sqf
  addons/medic_vehicle/readme.md
  addons/medic_vehicle/script_component.hpp
  addons/medic_vehicle/stringtable.xml
  addons/teleport/initSettings.inc.sqf
  addons/teleport/stringtable.xml
Labels: feature request

#118 Misc-fixes
  .hemtt/launch.toml
  addons/discord_richpresence/stringtable.xml
  addons/grad_screenshotmode/stringtable.xml
  addons/insignias/stringtable.xml
  addons/main/readme.md
  addons/main/script_debug.hpp
  addons/main/script_macros.hpp
  addons/rsr_itc_compat/stringtable.xml
  addons/signalpanel/stringtable.xml
  addons/teleport/stringtable.xml
  addons/uniforms/stringtable.xml
  addons/w_buildingshield/Cfg3DEN.hpp
  addons/w_buildingshield/CfgVehicles.hpp
  addons/w_buildingshield/stringtable.xml
  addons/w_teleporter/stringtable.xml
  addons/w_vehicleshield/Cfg3DEN.hpp
  addons/w_vehicleshield/stringtable.xml
  readme.md
Labels: enhancement

#128 o7<stein Intel implementiert
  addons/intel/$PBOPREFIX$
  addons/intel/CfgEventHandlers.hpp
  addons/intel/XEH_PREP.hpp
  addons/intel/XEH_preInit.sqf
  addons/intel/config.cpp
  addons/intel/functions/fnc_addIntel.sqf
  addons/intel/readme.md
  addons/intel/script_component.hpp
  addons/intel/stringtable.xml
  tools/debugMP.bat
Labels: feature request

#127 dismantle - add new component
  .hemtt/missions/ttt_test.VR/cba_settings.sqf
  addons/dismantle/$PBOPREFIX$
  addons/dismantle/CfgEventHandlers.hpp
  addons/dismantle/XEH_PREP.hpp
  addons/dismantle/XEH_postInit.sqf
  addons/dismantle/XEH_preInit.sqf
  addons/dismantle/XEH_preStart.sqf
  addons/dismantle/config.cpp
  addons/dismantle/functions/fnc_addActions.sqf
  addons/dismantle/functions/fnc_canDismantle.sqf
  addons/dismantle/functions/fnc_cancel.sqf
  addons/dismantle/functions/fnc_dismantleProgressbar.sqf
  addons/dismantle/functions/script_component.hpp
  addons/dismantle/initSettings.inc.sqf
  addons/dismantle/readme.md
  addons/dismantle/script_component.hpp
  addons/dismantle/stringtable.xml
Labels: feature request

#134 added images to signalpanel, buildingshield, vehicleshield, medic_backpack
  addons/medic_backpack/readme.md
  addons/signalpanel/readme.md
  addons/w_buildingshield/readme.md
  addons/w_vehicleshield/readme.md
Labels: enhancement

#140 stringtable sort, bump version number
  addons/advancedtowing/stringtable.xml
  addons/compat_3cb_vehicles/stringtable.xml
  addons/discord_richpresence/stringtable.xml
  addons/dismantle/stringtable.xml
  addons/intel/stringtable.xml
  addons/main/script_version.hpp
  addons/medic_backpack/stringtable.xml
  addons/medic_vehicle/stringtable.xml
  addons/repair_vehicle/stringtable.xml
  addons/rsr_vanilla_compat_ace/stringtable.xml
  addons/signalpanel/stringtable.xml
  addons/teleport/stringtable.xml
  addons/uniforms/stringtable.xml
  addons/w_teleporter/stringtable.xml
Labels: enhancement

#141 fix automatic version change
  mod.cpp
Labels: bug fix

#129 Update issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/enhancement_request.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: tools

#144 medic_vehicle, medic_backpack, repair, intel, signalpanel: ReadMe verbesserungen + kleine Fixes
  addons/intel/readme.md
  addons/medic_backpack/readme.md
  addons/medic_backpack/stringtable.xml
  addons/medic_vehicle/readme.md
  addons/medic_vehicle/stringtable.xml
  addons/repair_vehicle/readme.md
  addons/repair_vehicle/stringtable.xml
  addons/signalpanel/initSettings.inc.sqf
  addons/signalpanel/readme.md
Labels: enhancement

#150 tools - Rechtschreibung und Grammatik verbessert in Git Templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/enhancement_request.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: bug fix

#158 fix stringtables that were broken from folder rename
  addons/compat_vanilla_weapons/stringtable.xml
  addons/rsr_itc/stringtable.xml
Labels: bug fix

#154 Allgemein - Update authors
  authors.txt
Labels: enhancement

#156 signalpanel - fix default setting
  addons/signalpanel/initSettings.inc.sqf
Labels: bug fix

#148 Signs - Fix TTT signs and Violet flag
  .hemtt/missions/ttt_test.VR/mission.sqm
  addons/signs/CfgVehicles.hpp
Labels: bug fix

#165 use 2.18 alt syntax of deletevehicle
  .hemtt/missions/ttt_test.VR/mission.sqm
  addons/main/config.cpp
  addons/medic_backpack/functions/fnc_addActions.sqf
  addons/medic_backpack/functions/fnc_planeDeconstruct.sqf
  addons/uniforms/CfgWeapons.hpp
Labels: enhancement

#167 Main - FIX Blank line in Readme/Remove settings.json
  .vscode/settings.json
  addons/main/readme.md
Labels: bug fix

#168 repo - fix link error in readme
  readme.md
Labels: bug fix

#155 compat rhs weapons - Add rhs helmet change actions
  .hemtt/missions/ttt_test.VR/cba_settings.sqf
  .vscode/tasks.json
  addons/compat_rhs_weapons/$PBOPREFIX$
  addons/compat_rhs_weapons/CfgEventhandlers.hpp
  addons/compat_rhs_weapons/CfgWeapons.hpp
  addons/compat_rhs_weapons/XEH_PREP.hpp
  addons/compat_rhs_weapons/XEH_postInit.sqf
  addons/compat_rhs_weapons/XEH_preInit.sqf
  addons/compat_rhs_weapons/XEH_preStart.sqf
  addons/compat_rhs_weapons/config.cpp
  addons/compat_rhs_weapons/functions/fnc_addACEActions.sqf
  addons/compat_rhs_weapons/functions/fnc_handleSlotItemChanged.sqf
  addons/compat_rhs_weapons/functions/fnc_switchGoggles.sqf
  addons/compat_rhs_weapons/functions/fnc_switchVisor.sqf
  addons/compat_rhs_weapons/functions/script_component.hpp
  addons/compat_rhs_weapons/readme.md
  addons/compat_rhs_weapons/script_component.hpp
  addons/compat_rhs_weapons/stringtable.xml
Labels: feature request

#151 compat cup vehicles - Add improvements to FV432, GTL Boxer, M1038 Humvee, BTR-80/90, Bradley M2
  addons/compat_cup_vehicles/CfgVehicles.hpp
  addons/compat_cup_vehicles/config.cpp
  addons/compat_cup_vehicles/readme.md
Labels: enhancement

#153 compat_vanilla - added float to helis, update authors and required addons
  addons/compat_vanilla_vehicles/CfgVehicles.hpp
  addons/compat_vanilla_vehicles/config.cpp
  addons/compat_vanilla_vehicles/readme.md
Labels: feature request

#180 general - feature template hinzugefügt
  extras/feature_template/$PBOPREFIX$
  extras/feature_template/CfgEventHandlers.hpp
  extras/feature_template/XEH_PREP.hpp
  extras/feature_template/XEH_preInit.sqf
  extras/feature_template/XEH_preStart.sqf
  extras/feature_template/config.cpp
  extras/feature_template/functions/fnc_empty.sqf
  extras/feature_template/readme.md
  extras/feature_template/script_component.hpp
Labels: feature request

#183 tools - enable stringtable validation
  .github/workflows/main.yml
Labels: enhancement, tools

#182 general - improved stringtables to pass validator
  .vscode/tasks.json
  addons/advancedtowing/stringtable.xml
  addons/compat_3cb_vehicles/stringtable.xml
  addons/compat_rhs_weapons/stringtable.xml
  addons/medic_backpack/stringtable.xml
  addons/medic_vehicle/stringtable.xml
  addons/repair_vehicle/stringtable.xml
Labels: enhancement

#181 rsr_vanilla_compat_ace - removed compat, moved property to rsr_vanilla
  addons/rsr_vanilla/CfgVehicles.hpp
  addons/rsr_vanilla/config.cpp
  addons/rsr_vanilla_compat_ace/$PBOPREFIX$
  addons/rsr_vanilla_compat_ace/CfgVehicles.hpp
  addons/rsr_vanilla_compat_ace/config.cpp
  addons/rsr_vanilla_compat_ace/readme.md
  addons/rsr_vanilla_compat_ace/script_component.hpp
  addons/rsr_vanilla_compat_ace/stringtable.xml
Labels: enhancement

#190 w_teleporter - fix Übersetzung
  addons/w_teleporter/functions/fnc_onListPlayersSelChanged.sqf
  addons/w_teleporter/stringtable.xml
Labels: bug fix

#170 general - Fix addon name, Fix Scope Config
  addons/compat_rhs_ammo/config.cpp
  addons/compat_vanilla_weapons/CfgWeapons.hpp
  addons/compat_vanilla_weapons/config.cpp
  addons/compat_vanilla_weapons/script_component.hpp
  addons/discord_richpresence/config.cpp
  addons/grad_screenshotmode/config.cpp
Labels: enhancement

#191 general - improve readme markdown
  .github/ISSUE_TEMPLATE/enhancement_request.md
  .github/ISSUE_TEMPLATE/feature_request.md
  addons/intel/readme.md
  addons/main/readme.md
  addons/medic_backpack/readme.md
  addons/medic_vehicle/readme.md
  addons/repair_vehicle/readme.md
  addons/signalpanel/readme.md
Labels: enhancement

#185 general - update test mission
  .hemtt/missions/ttt_test.VR/mission.sqm
Labels: bug fix

#192 medic_vehicle, medic_backpack, repair_vehicle - disable Damage
  addons/medic_backpack/functions/fnc_planeConstruct.sqf
  addons/medic_vehicle/functions/fnc_tentConstruct.sqf
  addons/repair_vehicle/functions/fnc_workshopConstruct.sqf
Labels: bug fix

#195 w_vehicleshield - fix docs, fix function call for 3DEN
  addons/main/XEH_PREP.hpp
  addons/main/functions/fnc_callGlobalFnc.sqf
  addons/w_vehicleshield/XEH_PREP.hpp
  addons/w_vehicleshield/functions/fnc_addVehicleShield.sqf
Labels: bug fix

#187 general - add compat to fix xeh warnings
  addons/compat_xeh_fix/$PBOPREFIX$
  addons/compat_xeh_fix/compat_breach/CfgVehicles.hpp
  addons/compat_xeh_fix/compat_breach/config.cpp
  addons/compat_xeh_fix/compat_breach/readme.md
  addons/compat_xeh_fix/compat_breach/script_component.hpp
  addons/compat_xeh_fix/compat_bwmod/CfgVehicles.hpp
  addons/compat_xeh_fix/compat_bwmod/config.cpp
  addons/compat_xeh_fix/compat_bwmod/readme.md
  addons/compat_xeh_fix/compat_bwmod/script_component.hpp
  addons/compat_xeh_fix/compat_fir_aws/CfgVehicles.hpp
  addons/compat_xeh_fix/compat_fir_aws/config.cpp
  addons/compat_xeh_fix/compat_fir_aws/readme.md
  addons/compat_xeh_fix/compat_fir_aws/script_component.hpp
  addons/compat_xeh_fix/compat_pbw/CfgVehicles.hpp
  addons/compat_xeh_fix/compat_pbw/config.cpp
  addons/compat_xeh_fix/compat_pbw/readme.md
  addons/compat_xeh_fix/compat_pbw/script_component.hpp
  addons/compat_xeh_fix/compat_rnt/CfgVehicles.hpp
  addons/compat_xeh_fix/compat_rnt/config.cpp
  addons/compat_xeh_fix/compat_rnt/readme.md
  addons/compat_xeh_fix/compat_rnt/script_component.hpp
  addons/compat_xeh_fix/compat_vanilla/CfgVehicles.hpp
  addons/compat_xeh_fix/compat_vanilla/config.cpp
  addons/compat_xeh_fix/compat_vanilla/readme.md
  addons/compat_xeh_fix/compat_vanilla/script_component.hpp
  addons/compat_xeh_fix/config.cpp
  addons/compat_xeh_fix/readme.md
  addons/compat_xeh_fix/script_component.hpp
Labels: bug fix
