Repository TacticalTrainingTeam/ttt_a3, pull requests merged in 2025-04, with the labels that each got.

#296 effects - fix readme
  addons/effects/readme.md
Labels: ignore-changelog

#295 common - Add ACE fortify presets
  .hemtt/missions/ttt_test.VR/mission.sqm
  addons/common/config.cpp
  addons/common/configs/ACE_Fortify.hpp
  addons/common/readme.md
Labels: pr/feature

#291 uniforms - Improve Config, Add Platin Tropentarn
  addons/uniforms/CfgVehicles.hpp
  addons/uniforms/CfgWeapons.hpp
  addons/uniforms/config.cpp
  addons/uniforms/data/pictures/ttt_uniform_platinum_bw_tropen_ca.paa
  addons/uniforms/stringtable.xml
Labels: pr/enhancement

#288 common - Add UAV and Mark Crate
  addons/common/CfgVehicles.hpp
  addons/common/config.cpp
  addons/common/configs/crates_engineer.hpp
  addons/common/configs/crates_other.hpp
  addons/common/readme.md
  addons/common/stringtable.xml
Labels: pr/enhancement

#257 common - Add more units
  addons/common/CfgVehicles.hpp
  addons/common/config.cpp
  addons/common/configs/extra_units.hpp
  addons/common/readme.md
  addons/common/stringtable.xml
Labels: pr/feature

#297 general - Prepare release
  addons/common/stringtable.xml
  addons/effects/stringtable.xml
  addons/main/script_version.hpp
  addons/uniforms/stringtable.xml
Labels: ignore-changelog

#298 tools - Add cDLCs to launch configs
  .hemtt/launch.toml
Labels: tools

#301 fix breath + colorCorrection
  addons/effects/CfgSounds.hpp
  addons/effects/CfgVehicles.hpp
  addons/effects/XEH_PREP.hpp
  addons/effects/functions/fnc_condensedBreath.sqf
  addons/effects/functions/fnc_condensedBreathEffects.sqf
  addons/effects/functions/fnc_condensedBreathInit.sqf
  addons/effects/functions/fnc_stormEffects.sqf
  addons/effects/functions/fnc_zenRegister.sqf
  addons/effects/readme.md
Labels: pr/bug-fix

#306 uniform - Fix Config `:`
  addons/uniforms/CfgVehicles.hpp
Labels: pr/change, ignore-changelog

#307 tools - Update readme
  readme.md
Labels: tools

#309 medic_backpack - change light classname in readme example
  addons/medic_backpack/readme.md
Labels: ignore-changelog

#310 rsr - fix function `removeTurretWeapon`
  addons/rsr/CfgEventHandlers.hpp
  addons/rsr/XEH_PREP.hpp
  addons/rsr/XEH_preInit.sqf
  addons/rsr/XEH_preStart.sqf
  addons/rsr/config.cpp
  addons/rsr/functions/fnc_removeTurretWeapon.sqf
  addons/rsr/readme.md
  addons/rsr/rsr_retex_vanilla/readme.md
Labels: pr/bug-fix

#312 compat_cup_units_trenches - fix config value
  addons/compat_cup_units/compat_cup_units_trenches/CfgVehicles.hpp
  addons/compat_cup_units/compat_cup_units_trenches/CfgWeapons.hpp
Labels: pr/bug-fix, ignore-changelog

#308 common - Add crate with parachutes and altimeters
  addons/common/configs/crates_other.hpp
  addons/common/readme.md
  addons/common/stringtable.xml
Labels: pr/feature

#311 new component - Add `compat_3cb_equipment`
  addons/compat_3cb_equipment/$PBOPREFIX$
  addons/compat_3cb_equipment/CfgVehicles.hpp
  addons/compat_3cb_equipment/compat_3cb_equipment_logistics/CfgVehicles.hpp
  addons/compat_3cb_equipment/compat_3cb_equipment_logistics/README.md
  addons/compat_3cb_equipment/compat_3cb_equipment_logistics/config.cpp
  addons/compat_3cb_equipment/compat_3cb_equipment_logistics/script_component.hpp
  addons/compat_3cb_equipment/compat_3cb_equipment_trenches/CfgVehicles.hpp
  addons/compat_3cb_equipment/compat_3cb_equipment_trenches/README.md
  addons/compat_3cb_equipment/compat_3cb_equipment_trenches/config.cpp
  addons/compat_3cb_equipment/compat_3cb_equipment_trenches/script_component.hpp
  addons/compat_3cb_equipment/config.cpp
  addons/compat_3cb_equipment/readme.md
  addons/compat_3cb_equipment/script_component.hpp
Labels: pr/feature

#303 common - Add Composition with HC, Zeus, Spectator, Respawn
  .hemtt/missions/ttt_test.VR/mission.sqm
  addons/common/Cfg3DEN.hpp
  addons/common/compositions/TTT-Basis-Module/composition.sqe
  addons/common/compositions/TTT-Basis-Module/header.sqe
  addons/common/config.cpp
  addons/common/readme.md
Labels: pr/feature

#313 fix error
  addons/compat_rnt/compat_rnt_fuchs/script_component.hpp
Labels: pr/bug-fix, ignore-changelog

#314 common - Fix-composition
  addons/common/Cfg3DEN.hpp
  addons/common/compositions/basisModule/composition.sqe
  addons/common/compositions/basisModule/header.sqe
  addons/common/readme.md
Labels: pr/bug-fix, ignore-changelog

#316 tools - Prepare-release
  addons/common/stringtable.xml
  addons/main/script_version.hpp
Labels: ignore-changelog

#315 New Component - Add ITC Compat for CUP Vehicles (M270)
  addons/compat_cup_vehicles/compat_cup_vehicles_itc/CfgITCLandBalistics.hpp
  addons/compat_cup_vehicles/compat_cup_vehicles_itc/CfgMagazines.hpp
  addons/compat_cup_vehicles/compat_cup_vehicles_itc/CfgVehicles.hpp
  addons/compat_cup_vehicles/compat_cup_vehicles_itc/CfgWeapons.hpp
  addons/compat_cup_vehicles/compat_cup_vehicles_itc/config.cpp
  addons/compat_cup_vehicles/compat_cup_vehicles_itc/readme.md
  addons/compat_cup_vehicles/compat_cup_vehicles_itc/script_component.hpp
  addons/compat_cup_vehicles/compat_cup_vehicles_itc/stringtable.xml
Labels: pr/feature

#300 New Component - Add ITC Compats for BWA3 (PzH2000)
  addons/compat_bwa3/compat_bwa3_itc/CfgITCLandBallistics.hpp
  addons/compat_bwa3/compat_bwa3_itc/CfgMagazines.hpp
  addons/compat_bwa3/compat_bwa3_itc/CfgVehicles.hpp
  addons/compat_bwa3/compat_bwa3_itc/CfgWeapons.hpp
  addons/compat_bwa3/compat_bwa3_itc/CfgWeapons_Magazines.hpp
  addons/compat_bwa3/compat_bwa3_itc/CfgXEH.hpp
  addons/compat_bwa3/compat_bwa3_itc/ballistics/pzh2000_ch1_ha.sqf
  addons/compat_bwa3/compat_bwa3_itc/ballistics/pzh2000_ch1_la.sqf
  addons/compat_bwa3/compat_bwa3_itc/ballistics/pzh2000_ch2_ha.sqf
  addons/compat_bwa3/compat_bwa3_itc/ballistics/pzh2000_ch2_la.sqf
  addons/compat_bwa3/compat_bwa3_itc/ballistics/pzh2000_ch3_ha.sqf
  addons/compat_bwa3/compat_bwa3_itc/ballistics/pzh2000_ch3_la.sqf
  addons/compat_bwa3/compat_bwa3_itc/ballistics/pzh2000_ch4_ha.sqf
  addons/compat_bwa3/compat_bwa3_itc/ballistics/pzh2000_ch4_la.sqf
  addons/compat_bwa3/compat_bwa3_itc/ballistics/pzh2000_ch5_ha.sqf
  addons/compat_bwa3/compat_bwa3_itc/ballistics/pzh2000_ch5_la.sqf
  addons/compat_bwa3/compat_bwa3_itc/ballistics/pzh2000_list.sqf
  addons/compat_bwa3/compat_bwa3_itc/config.cpp
  addons/compat_bwa3/compat_bwa3_itc/script_component.hpp
  addons/compat_bwa3/compat_bwa3_itc/stringtable.xml
  addons/compat_bwa3/readme.md
  addons/main/script_macros.hpp
Labels: pr/feature

#318 compat_cup_vehicles_itc - Fix Stringtable
  addons/compat_cup_vehicles/compat_cup_vehicles_itc/CfgVehicles.hpp
Labels: pr/bug-fix

#317 tools - improve readme
  addons/common/readme.md
  readme.md
Labels: tools

#320 compat_vanilla - Add subaddon for ITC
  addons/compat_vanilla/compat_vanilla_itc/CfgVehicles.hpp
  addons/compat_vanilla/compat_vanilla_itc/config.cpp
  addons/compat_vanilla/compat_vanilla_itc/readme.md
  addons/compat_vanilla/compat_vanilla_itc/script_component.hpp
  addons/compat_vanilla/compat_vanilla_itc/stringtable.xml
Labels: pr/feature

#321 common - Add Atmospheric Flak Fire Function
  .hemtt/missions/ttt_test.VR/mission.sqm
  addons/common/XEH_PREP.hpp
  addons/common/functions/fnc_doFlakFire.sqf
  addons/common/readme.md
Labels: pr/feature

#322 general - Improve every readme
  addons/advancedslingloading/readme.md
  addons/advancedtowing/readme.md
  addons/backpacks/readme.md
  addons/berets/readme.md
  addons/common/readme.md
  addons/compat_3cb_equipment/compat_3cb_equipment_logistics/README.md
  addons/compat_3cb_equipment/compat_3cb_equipment_trenches/README.md
  addons/compat_3cb_equipment/readme.md
  addons/compat_3cb_factions/compat_3cb_factions_trenches/README.md
  addons/compat_3cb_factions/readme.md
  addons/compat_3cb_vehicles/readme.md
  addons/compat_bwa3/compat_bwa3_itc/readme.md
  addons/compat_bwa3/readme.md
  addons/compat_cfp/compat_cfp_logistics/README.md
  addons/compat_cfp/readme.md
  addons/compat_cup_units/compat_cup_units_trenches/README.md
  addons/compat_cup_units/readme.md
  addons/compat_cup_vehicles/compat_cup_vehicles_itc/readme.md
  addons/compat_cup_vehicles/readme.md
  addons/compat_rhs/readme.md
  addons/compat_rnt/README.md
  addons/compat_rnt/compat_rnt_gmw/README.md
  addons/compat_rnt/compat_rnt_m120/README.md
  addons/compat_rnt/compat_rnt_mg3/README.md
  addons/compat_vanilla/compat_vanilla_itc/readme.md
  addons/compat_vanilla/readme.md
  addons/compat_xeh_fix/readme.md
  addons/dismantle/readme.md
  addons/effects/readme.md
  addons/grad_screenshotmode/readme.md
  addons/helmets/readme.md
  addons/insignias/insignias_tagging/readme.md
  addons/insignias/readme.md
  addons/intel/readme.md
  addons/medic_backpack/readme.md
  addons/medic_vehicle/readme.md
  addons/repair_vehicle/readme.md
  addons/rsr/readme.md
  addons/rsr/rsr_retex_bwa3/readme.md
  addons/rsr/rsr_retex_cup/readme.md
  addons/rsr/rsr_retex_itc/readme.md
  addons/rsr/rsr_retex_rhs/readme.md
  addons/rsr/rsr_retex_vanilla/readme.md
  addons/signalpanel/readme.md
  addons/signs/readme.md
  addons/teleport/readme.md
  addons/uniforms/readme.md
  addons/vests/readme.md
  addons/w_buildingshield/readme.md
  addons/w_vehicleshield/readme.md
Labels: pr/enhancement

#323 compat_xeh - Remove obsolete PBW subaddon
  addons/compat_xeh_fix/compat_xeh_fix_pbw/CfgVehicles.hpp
  addons/compat_xeh_fix/compat_xeh_fix_pbw/config.cpp
  addons/compat_xeh_fix/compat_xeh_fix_pbw/readme.md
  addons/compat_xeh_fix/compat_xeh_fix_pbw/script_component.hpp
Labels: pr/cleanup

#327 tools - remove check string script
  .github/workflows/main.yml
  .vscode/tasks.json
  tools/check_strings.py
Labels: tools

#325 common - Improve `fnc_callReinforcement`
  .hemtt/missions/ttt_test.VR/mission.sqm
  addons/common/functions/fnc_callReinforcements.sqf
Labels: pr/optimization

#328 tools - remove unused script
  tools/search_undefined_function.py
Labels: tools
