Repository TacticalTrainingTeam/ttt_a3, pull requests merged in 2025-05, with the labels that each got.

#324 common - Fix Parachute Crate being unplacable in zeus
  addons/common/config.cpp
Labels: pr/bug-fix

#329 common - Fix `#adminVoted` and `#adminLogged` Slots, Remove extra Layer
  addons/common/compositions/basisModule/composition.sqe
Labels: pr/bug-fix

#319 common - Improve Fortify GM Preset, Add Camping Preset
  addons/common/configs/ACE_Fortify.hpp
Labels: pr/enhancement

#330 Prepare-release
  addons/compat_bwa3/compat_bwa3_itc/stringtable.xml
  addons/compat_vanilla/compat_vanilla_itc/stringtable.xml
  addons/main/script_version.hpp
Labels: ignore-changelog

#331 general - Improve Code with hemtt pedantic suggestions
  addons/advancedslingloading/functions/fnc_initAdvancedSlingLoading.sqf
  addons/advancedtowing/functions/fnc_initAdvancedTowing.sqf
  addons/common/functions/fnc_callReinforcements.sqf
  addons/compat_bwa3/compat_bwa3_itc/CfgWeapons.hpp
  addons/compat_bwa3/compat_bwa3_itc/CfgXEH.hpp
  addons/compat_cup_vehicles/compat_cup_vehicles_itc/CfgWeapons.hpp
  addons/compat_rnt/compat_rnt_m120/CfgVehicles.hpp
  addons/spotlight_cup/CfgMainMenuSpotlight.hpp
  addons/spotlight_event/CfgMainMenuSpotlight.hpp
  addons/spotlight_rhs/CfgMainMenuSpotlight.hpp
  addons/w_buildingshield/functions/fnc_moduleBuildingShield.sqf
Labels: pr/enhancement

#333 comon - Fix `callReinforcements` params validation
  addons/common/functions/fnc_callReinforcements.sqf
  addons/main/script_version.hpp
Labels: pr/bug-fix

#286 counterAri - Add new Component
  .hemtt/missions/ttt_test.VR/mission.sqm
  addons/counterari/$PBOPREFIX$
  addons/counterari/CfgEventHandlers.hpp
  addons/counterari/CfgVehicles.hpp
  addons/counterari/XEH_PREP.hpp
  addons/counterari/XEH_preInit.sqf
  addons/counterari/XEH_preStart.sqf
  addons/counterari/config.cpp
  addons/counterari/functions/fnc_counterFire.sqf
  addons/counterari/functions/fnc_fireMission.sqf
  addons/counterari/functions/fnc_initEnemyAri.sqf
  addons/counterari/functions/fnc_initFriendlyAri.sqf
  addons/counterari/functions/fnc_positionFire.sqf
  addons/counterari/readme.md
  addons/counterari/script_component.hpp
  addons/counterari/stringtable.xml
Labels: pr/feature

#334 intel - move `intel` to `common`
  addons/common/XEH_PREP.hpp
  addons/common/functions/fnc_addIntel.sqf
  addons/common/readme.md
  addons/common/stringtable.xml
  addons/intel/$PBOPREFIX$
  addons/intel/CfgEventHandlers.hpp
  addons/intel/XEH_PREP.hpp
  addons/intel/XEH_preInit.sqf
  addons/intel/config.cpp
  addons/intel/readme.md
  addons/intel/script_component.hpp
  addons/intel/stringtable.xml
Labels: pr/change

#332 common - Improve readme
  addons/common/readme.md
Labels: ignore-changelog

#335 common - Add Funny Pictures
  addons/common/data/p_nettHier_ca.paa
  addons/common/data/p_rollatorgang_ca.paa
  addons/common/data/p_wantYou_ca.paa
  addons/common/readme.md
Labels: pr/feature

#337 fix default params
  addons/common/functions/fnc_callReinforcements.sqf
Labels: pr/bug-fix

#338 common - Update readme for intel
  addons/common/functions/fnc_addIntel.sqf
  addons/common/readme.md
Labels: ignore-changelog

#339 insignias_tagging - Add Memes
  addons/insignias/insignias_tagging/CfgTags.hpp
  addons/insignias/insignias_tagging/CfgWeapons.hpp
  addons/insignias/insignias_tagging/stringtable.xml
Labels: pr/feature

#342 tools - improve release drafter
  .github/release-drafter.yml
Labels: tools

#341 common, couterari - Improve Readme
  addons/common/readme.md
  addons/counterari/readme.md
Labels: pr/documentation

#343 tools/release drafter - Fix headings in changelog, Add Version Resolver
  .github/release-drafter.yml
  .github/workflows/release-drafter.yml
Labels: tools

#344 dismantle - Fix Condition for action to display
  .hemtt/missions/ttt_test.VR/cba_settings.sqf
  addons/dismantle/functions/fnc_canDismantle.sqf
Labels: pr/bug-fix

#349 compat_bwa3 - Improve Anim Interaction
  addons/compat_bwa3/CfgVehicles.hpp
  addons/compat_bwa3/config.cpp
  addons/compat_bwa3/readme.md
  addons/rsr/rsr_retex_bwa3/CfgVehicles.hpp
Labels: pr/enhancement

#350 tools - Fix dokumentation in `release-drafter.yml`
  .github/release-drafter.yml
Labels: tools

#351 Allgemein - clean up all script components
  addons/advancedslingloading/script_component.hpp
  addons/advancedtowing/script_component.hpp
  addons/backpacks/script_component.hpp
  addons/berets/script_component.hpp
  addons/clearhud/script_component.hpp
  addons/common/script_component.hpp
  addons/compat_3cb_equipment/script_component.hpp
  addons/compat_3cb_factions/script_component.hpp
  addons/compat_3cb_vehicles/script_component.hpp
  addons/compat_bwa3/script_component.hpp
  addons/compat_cfp/script_component.hpp
  addons/compat_cup_units/script_component.hpp
  addons/compat_cup_vehicles/script_component.hpp
  addons/compat_rhs/script_component.hpp
  addons/compat_rnt/script_component.hpp
  addons/compat_vanilla/script_component.hpp
  addons/compat_xeh_fix/script_component.hpp
  addons/counterari/script_component.hpp
  addons/discord_richpresence/script_component.hpp
  addons/dismantle/script_component.hpp
  addons/effects/script_component.hpp
  addons/grad_screenshotmode/script_component.hpp
  addons/helmets/script_component.hpp
  addons/insignias/script_component.hpp
  addons/main/script_component.hpp
  addons/medic_backpack/script_component.hpp
  addons/medic_vehicle/script_component.hpp
  addons/repair_vehicle/script_component.hpp
  addons/rsr/script_component.hpp
  addons/signalpanel/script_component.hpp
  addons/signs/script_component.hpp
  addons/spotlight_cup/script_component.hpp
  addons/spotlight_event/script_component.hpp
  addons/spotlight_rhs/script_component.hpp
  addons/teleport/script_component.hpp
  addons/uniforms/script_component.hpp
  addons/vests/script_component.hpp
  addons/w_buildingshield/script_component.hpp
  addons/w_teleporter/script_component.hpp
  addons/w_vehicleshield/script_component.hpp
  extras/feature_template/script_component.hpp
Labels: pr/cleanup

#364 Prepare release
  addons/common/stringtable.xml
  addons/counterari/stringtable.xml
  addons/insignias/insignias_tagging/stringtable.xml
  addons/main/script_version.hpp
Labels: ignore-changelog

#365 GRAD Screenshotmode - Remove component
  addons/grad_screenshotmode/$PBOPREFIX$
  addons/grad_screenshotmode/CfgEventHandlers.hpp
  addons/grad_screenshotmode/XEH_PREP.hpp
  addons/grad_screenshotmode/XEH_postInit.sqf
  addons/grad_screenshotmode/XEH_preInit.sqf
  addons/grad_screenshotmode/XEH_preStart.sqf
  addons/grad_screenshotmode/config.cpp
  addons/grad_screenshotmode/functions/fnc_addHelpRecord.sqf
  addons/grad_screenshotmode/functions/fnc_toggleACENametags.sqf
  addons/grad_screenshotmode/functions/fnc_toggleAll.sqf
  addons/grad_screenshotmode/functions/fnc_toggleDuiHud.sqf
  addons/grad_screenshotmode/functions/fnc_toggleVanillaHUD.sqf
  addons/grad_screenshotmode/readme.md
  addons/grad_screenshotmode/script_component.hpp
  addons/grad_screenshotmode/stringtable.xml
Labels: pr/change

#363 Screenshot mode - Add new Component
  .hemtt/launch.toml
  .hemtt/missions/ttt_test.VR/mission.sqm
  addons/screenshotmode/$PBOPREFIX$
  addons/screenshotmode/CfgEventHandlers.hpp
  addons/screenshotmode/XEH_PREP.hpp
  addons/screenshotmode/XEH_preInit.sqf
  addons/screenshotmode/XEH_preStart.sqf
  addons/screenshotmode/config.cpp
  addons/screenshotmode/functions/fnc_addEventHandler.sqf
  addons/screenshotmode/readme.md
  addons/screenshotmode/script_component.hpp
Labels: pr/feature

#367 Common - Add Numbers to ACE Tagging
  .hemtt/missions/~ttt_test.vr/mission.sqm
  addons/common/config.cpp
  addons/common/configs/ACE_Tagging.hpp
  addons/common/data/Zahl_0_ca.paa
  addons/common/data/Zahl_1_ca.paa
  addons/common/data/Zahl_2_ca.paa
  addons/common/data/Zahl_3_ca.paa
  addons/common/data/Zahl_4_ca.paa
  addons/common/data/Zahl_5_ca.paa
  addons/common/data/Zahl_6_ca.paa
  addons/common/data/Zahl_7_ca.paa
  addons/common/data/Zahl_8_ca.paa
  addons/common/data/Zahl_9_ca.paa
  addons/common/data/p_propertyOfTTT_ca.paa
Labels: pr/feature

#371 general - Prepare release
  addons/main/script_version.hpp
  addons/mpls/stringtable.xml
Labels: ignore-changelog
